###################################################################

# Created by write_sdc on Sat Nov 29 13:33:31 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -power mW -voltage V       \
-current mA
set_wire_load_mode top
set_load -pin_load 0.05 [get_ports {O_re[25]}]
set_load -pin_load 0.05 [get_ports {O_re[24]}]
set_load -pin_load 0.05 [get_ports {O_re[23]}]
set_load -pin_load 0.05 [get_ports {O_re[22]}]
set_load -pin_load 0.05 [get_ports {O_re[21]}]
set_load -pin_load 0.05 [get_ports {O_re[20]}]
set_load -pin_load 0.05 [get_ports {O_re[19]}]
set_load -pin_load 0.05 [get_ports {O_re[18]}]
set_load -pin_load 0.05 [get_ports {O_re[17]}]
set_load -pin_load 0.05 [get_ports {O_re[16]}]
set_load -pin_load 0.05 [get_ports {O_re[15]}]
set_load -pin_load 0.05 [get_ports {O_re[14]}]
set_load -pin_load 0.05 [get_ports {O_re[13]}]
set_load -pin_load 0.05 [get_ports {O_re[12]}]
set_load -pin_load 0.05 [get_ports {O_re[11]}]
set_load -pin_load 0.05 [get_ports {O_re[10]}]
set_load -pin_load 0.05 [get_ports {O_re[9]}]
set_load -pin_load 0.05 [get_ports {O_re[8]}]
set_load -pin_load 0.05 [get_ports {O_re[7]}]
set_load -pin_load 0.05 [get_ports {O_re[6]}]
set_load -pin_load 0.05 [get_ports {O_re[5]}]
set_load -pin_load 0.05 [get_ports {O_re[4]}]
set_load -pin_load 0.05 [get_ports {O_re[3]}]
set_load -pin_load 0.05 [get_ports {O_re[2]}]
set_load -pin_load 0.05 [get_ports {O_re[1]}]
set_load -pin_load 0.05 [get_ports {O_re[0]}]
set_load -pin_load 0.05 [get_ports {O_im[25]}]
set_load -pin_load 0.05 [get_ports {O_im[24]}]
set_load -pin_load 0.05 [get_ports {O_im[23]}]
set_load -pin_load 0.05 [get_ports {O_im[22]}]
set_load -pin_load 0.05 [get_ports {O_im[21]}]
set_load -pin_load 0.05 [get_ports {O_im[20]}]
set_load -pin_load 0.05 [get_ports {O_im[19]}]
set_load -pin_load 0.05 [get_ports {O_im[18]}]
set_load -pin_load 0.05 [get_ports {O_im[17]}]
set_load -pin_load 0.05 [get_ports {O_im[16]}]
set_load -pin_load 0.05 [get_ports {O_im[15]}]
set_load -pin_load 0.05 [get_ports {O_im[14]}]
set_load -pin_load 0.05 [get_ports {O_im[13]}]
set_load -pin_load 0.05 [get_ports {O_im[12]}]
set_load -pin_load 0.05 [get_ports {O_im[11]}]
set_load -pin_load 0.05 [get_ports {O_im[10]}]
set_load -pin_load 0.05 [get_ports {O_im[9]}]
set_load -pin_load 0.05 [get_ports {O_im[8]}]
set_load -pin_load 0.05 [get_ports {O_im[7]}]
set_load -pin_load 0.05 [get_ports {O_im[6]}]
set_load -pin_load 0.05 [get_ports {O_im[5]}]
set_load -pin_load 0.05 [get_ports {O_im[4]}]
set_load -pin_load 0.05 [get_ports {O_im[3]}]
set_load -pin_load 0.05 [get_ports {O_im[2]}]
set_load -pin_load 0.05 [get_ports {O_im[1]}]
set_load -pin_load 0.05 [get_ports {O_im[0]}]
set_load -pin_load 0.05 [get_ports out_valid]
set_max_fanout 32 [get_ports rst_n]
create_clock [get_ports clk]  -period 14  -waveform {0 7}
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  7  [get_ports {D_re[15]}]
set_input_delay -clock clk  7  [get_ports {D_re[14]}]
set_input_delay -clock clk  7  [get_ports {D_re[13]}]
set_input_delay -clock clk  7  [get_ports {D_re[12]}]
set_input_delay -clock clk  7  [get_ports {D_re[11]}]
set_input_delay -clock clk  7  [get_ports {D_re[10]}]
set_input_delay -clock clk  7  [get_ports {D_re[9]}]
set_input_delay -clock clk  7  [get_ports {D_re[8]}]
set_input_delay -clock clk  7  [get_ports {D_re[7]}]
set_input_delay -clock clk  7  [get_ports {D_re[6]}]
set_input_delay -clock clk  7  [get_ports {D_re[5]}]
set_input_delay -clock clk  7  [get_ports {D_re[4]}]
set_input_delay -clock clk  7  [get_ports {D_re[3]}]
set_input_delay -clock clk  7  [get_ports {D_re[2]}]
set_input_delay -clock clk  7  [get_ports {D_re[1]}]
set_input_delay -clock clk  7  [get_ports {D_re[0]}]
set_input_delay -clock clk  7  [get_ports {D_im[15]}]
set_input_delay -clock clk  7  [get_ports {D_im[14]}]
set_input_delay -clock clk  7  [get_ports {D_im[13]}]
set_input_delay -clock clk  7  [get_ports {D_im[12]}]
set_input_delay -clock clk  7  [get_ports {D_im[11]}]
set_input_delay -clock clk  7  [get_ports {D_im[10]}]
set_input_delay -clock clk  7  [get_ports {D_im[9]}]
set_input_delay -clock clk  7  [get_ports {D_im[8]}]
set_input_delay -clock clk  7  [get_ports {D_im[7]}]
set_input_delay -clock clk  7  [get_ports {D_im[6]}]
set_input_delay -clock clk  7  [get_ports {D_im[5]}]
set_input_delay -clock clk  7  [get_ports {D_im[4]}]
set_input_delay -clock clk  7  [get_ports {D_im[3]}]
set_input_delay -clock clk  7  [get_ports {D_im[2]}]
set_input_delay -clock clk  7  [get_ports {D_im[1]}]
set_input_delay -clock clk  7  [get_ports {D_im[0]}]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  7  [get_ports in_valid]
set_output_delay -clock clk  7  [get_ports {O_re[25]}]
set_output_delay -clock clk  7  [get_ports {O_re[24]}]
set_output_delay -clock clk  7  [get_ports {O_re[23]}]
set_output_delay -clock clk  7  [get_ports {O_re[22]}]
set_output_delay -clock clk  7  [get_ports {O_re[21]}]
set_output_delay -clock clk  7  [get_ports {O_re[20]}]
set_output_delay -clock clk  7  [get_ports {O_re[19]}]
set_output_delay -clock clk  7  [get_ports {O_re[18]}]
set_output_delay -clock clk  7  [get_ports {O_re[17]}]
set_output_delay -clock clk  7  [get_ports {O_re[16]}]
set_output_delay -clock clk  7  [get_ports {O_re[15]}]
set_output_delay -clock clk  7  [get_ports {O_re[14]}]
set_output_delay -clock clk  7  [get_ports {O_re[13]}]
set_output_delay -clock clk  7  [get_ports {O_re[12]}]
set_output_delay -clock clk  7  [get_ports {O_re[11]}]
set_output_delay -clock clk  7  [get_ports {O_re[10]}]
set_output_delay -clock clk  7  [get_ports {O_re[9]}]
set_output_delay -clock clk  7  [get_ports {O_re[8]}]
set_output_delay -clock clk  7  [get_ports {O_re[7]}]
set_output_delay -clock clk  7  [get_ports {O_re[6]}]
set_output_delay -clock clk  7  [get_ports {O_re[5]}]
set_output_delay -clock clk  7  [get_ports {O_re[4]}]
set_output_delay -clock clk  7  [get_ports {O_re[3]}]
set_output_delay -clock clk  7  [get_ports {O_re[2]}]
set_output_delay -clock clk  7  [get_ports {O_re[1]}]
set_output_delay -clock clk  7  [get_ports {O_re[0]}]
set_output_delay -clock clk  7  [get_ports {O_im[25]}]
set_output_delay -clock clk  7  [get_ports {O_im[24]}]
set_output_delay -clock clk  7  [get_ports {O_im[23]}]
set_output_delay -clock clk  7  [get_ports {O_im[22]}]
set_output_delay -clock clk  7  [get_ports {O_im[21]}]
set_output_delay -clock clk  7  [get_ports {O_im[20]}]
set_output_delay -clock clk  7  [get_ports {O_im[19]}]
set_output_delay -clock clk  7  [get_ports {O_im[18]}]
set_output_delay -clock clk  7  [get_ports {O_im[17]}]
set_output_delay -clock clk  7  [get_ports {O_im[16]}]
set_output_delay -clock clk  7  [get_ports {O_im[15]}]
set_output_delay -clock clk  7  [get_ports {O_im[14]}]
set_output_delay -clock clk  7  [get_ports {O_im[13]}]
set_output_delay -clock clk  7  [get_ports {O_im[12]}]
set_output_delay -clock clk  7  [get_ports {O_im[11]}]
set_output_delay -clock clk  7  [get_ports {O_im[10]}]
set_output_delay -clock clk  7  [get_ports {O_im[9]}]
set_output_delay -clock clk  7  [get_ports {O_im[8]}]
set_output_delay -clock clk  7  [get_ports {O_im[7]}]
set_output_delay -clock clk  7  [get_ports {O_im[6]}]
set_output_delay -clock clk  7  [get_ports {O_im[5]}]
set_output_delay -clock clk  7  [get_ports {O_im[4]}]
set_output_delay -clock clk  7  [get_ports {O_im[3]}]
set_output_delay -clock clk  7  [get_ports {O_im[2]}]
set_output_delay -clock clk  7  [get_ports {O_im[1]}]
set_output_delay -clock clk  7  [get_ports {O_im[0]}]
set_output_delay -clock clk  7  [get_ports out_valid]
